ElevenLabs/Packages/com.rest.elevenlabs/Documentation~/README.md
ElevenLabs/Packages/com.rest.elevenlabs/Editor/ElevenLabs.Editor.asmdef
ElevenLabs/Packages/com.rest.elevenlabs/Editor/ElevenLabsConfigurationSettingsInspector.cs
ElevenLabs/Packages/com.rest.elevenlabs/Editor/ElevenLabsEditorWindow.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/BaseEndPoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/ElevenLabs.asmdef
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/ElevenLabsClient.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/ElevenLabsClientSettings.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/ElevenLabsClientSettings.cs.meta
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/ElevenLabsConfigurationSettings.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/History/HistoryEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/History/HistoryItem.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/HttpResponseMessageExtensions.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/TextToSpeech/TextToSpeechEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/TextToSpeech/TextToSpeechRequest.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Users/UserEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/VoiceGeneration/VoiceGenerationEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Voices/VoicesEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Tests/Test_Fixture_00_Authentication.cs
ElevenLabs/Packages/com.rest.elevenlabs/Tests/Test_Fixture_00_Authentication.cs.meta
ElevenLabs/Packages/com.rest.elevenlabs/Tests/Test_Fixture_03_TextToSpeechEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Tests/Test_Fixture_04_HistoryEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json
README.md

- An attempt was made to try to Implement TTS streaming. Mostly works, but Unity bug prevents this feature until fixed.
- Added support for proxy api gateway
- Updated unit tests
- Fixed some more bugs in editor dashboard

com.rest.elevenlabs 1.1.0

---

ElevenLabs/Packages/com.rest.elevenlabs/Editor/ElevenLabsConfigurationSettingsInspector.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json

- fixed some issues with configuration settings inspector

com.rest.elevenlabs 1.1.1

---

ElevenLabs/Packages/com.rest.elevenlabs/Editor/ElevenLabsEditorWindow.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/ElevenLabsClient.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Models.meta
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Models/Language.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Models/Language.cs.meta
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Models/Model.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Models/Model.cs.meta
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Models/ModelsEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Models/ModelsEndpoint.cs.meta
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/TextToSpeech/TextToSpeechEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/TextToSpeech/TextToSpeechRequest.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Voices/Voice.cs
ElevenLabs/Packages/com.rest.elevenlabs/Tests/Test_Fixture_05_VoiceGeneration.cs
ElevenLabs/Packages/com.rest.elevenlabs/Tests/Test_Fixture_06_Models.cs
ElevenLabs/Packages/com.rest.elevenlabs/Tests/Test_Fixture_06_Models.cs.meta
ElevenLabs/Packages/com.rest.elevenlabs/package.json

- Added ModelsEndpoint
- Updated TextToSpeech.TextToSpeechAsync with optional Model parameter. Defaults to eleven_monolingual_v1
- Added default voices
- Updated editor window with new model option

com.rest.elevenlabs 1.3.0

---

ElevenLabs/Packages/com.rest.elevenlabs/Editor/VoicePropertyDrawer.cs
ElevenLabs/Packages/com.rest.elevenlabs/Editor/VoicePropertyDrawer.cs.meta
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Voices/Voice.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Voices/VoiceSettings.cs
ElevenLabs/Packages/com.rest.elevenlabs/Tests/Test_Fixture_03_TextToSpeechEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json
ElevenLabs/Packages/manifest.json
ElevenLabs/ProjectSettings/ProjectSettings.asset
ElevenLabs/ProjectSettings/UnityConnectSettings.asset

- Add ability to serialize voice and voice settings in inspector

com.rest.elevenlabs 1.3.1

---

ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Voices/Voice.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Voices/VoicesEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json

- Added voice equality operators
- Added better parameter checks in VoicesEndPoint

com.rest.elevenlabs 1.3.2

---

ElevenLabs/Packages/com.rest.elevenlabs/Runtime/TextToSpeech/TextToSpeechEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Voices/Voice.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json

- assign default voice names
- get voice details if missing in tts

com.rest.elevenlabs 1.3.3

---

ElevenLabs/Packages/com.rest.elevenlabs/Documentation~/README.md
ElevenLabs/Packages/com.rest.elevenlabs/Editor/ElevenLabs.Editor.asmdef
ElevenLabs/Packages/com.rest.elevenlabs/Editor/ElevenLabsEditorWindow.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json
ElevenLabs/Packages/manifest.json
ElevenLabs/ProjectSettings/ProjectVersion.txt
README.md

com.rest.elevenlabs 2.0.1

---

ElevenLabs/Packages/com.rest.elevenlabs/Editor/ElevenLabsConfigurationInspector.cs
ElevenLabs/Packages/com.rest.elevenlabs/Editor/VoicePropertyDrawer.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/ElevenLabsConfiguration.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json

- added a way to specify global voice setting in ElevenLabsConfiguration

com.rest.elevenlabs 2.0.2

---

ElevenLabs/Packages/com.rest.elevenlabs/Documentation~/README.md
ElevenLabs/Packages/com.rest.elevenlabs/package.json
README.md

com.rest.elevenlabs 2.0.3

---

ElevenLabs/Packages/com.rest.elevenlabs/Editor/ElevenLabsEditorWindow.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json

- fixed a bug when resetting voice options to default

com.rest.elevenlabs 2.0.4

---

ElevenLabs/Packages/com.rest.elevenlabs/Editor/ElevenLabsEditorWindow.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Voices/VoiceSettings.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json

- updated voice settings
- added speaker boost and style options

com.rest.elevenlabs 2.0.5

---

ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Voices/Voice.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json
ElevenLabs/Packages/manifest.json
ElevenLabs/ProjectSettings/ProjectVersion.txt

- Added Voice.HighQualityBaseModelIds
- bump deps

com.rest.elevenlabs 2.0.7

---

ElevenLabs/Packages/com.rest.elevenlabs/Runtime/VoiceGeneration/CreateVoiceRequest.cs
ElevenLabs/Packages/com.rest.elevenlabs/Tests/Test_Fixture_05_VoiceGeneration.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json

- Added CreateVoiceRequest.Description

com.rest.elevenlabs 2.0.8

---

ElevenLabs/Packages/com.rest.elevenlabs/Documentation~/README.md
ElevenLabs/Packages/com.rest.elevenlabs/Editor/VoiceClipUtilities.cs.meta
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/History/HistoryInfo.cs.meta
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/OutputFormat.cs.meta
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/OutputFormatExtensions.cs.meta
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/VoiceGeneration/GeneratedVoicePreviewRequest.cs.meta
ElevenLabs/Packages/com.rest.elevenlabs/Tests/Test_Fixture_04_HistoryEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json
README.md

- Fixed unit test
- Updated docs
- Added missing icons

com.rest.elevenlabs 3.0.1

---

ElevenLabs/Packages/com.rest.elevenlabs/Runtime/TextToSpeech/TextToSpeechEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json

- Fixed partial clip sample rate not being set correctly

com.rest.elevenlabs 3.0.2

---

ElevenLabs/Packages/com.rest.elevenlabs/package.json

- updated com.utilities.rest -> 2.2.5

com.rest.elevenlabs 3.0.3

---

.github/workflows/upm-subtree-split.yml
ElevenLabs/Packages/com.rest.elevenlabs/Editor/ElevenLabsDashboard.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json

com.rest.elevenlabs 3.0.4

---

ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Authentication/ElevenLabsSettings.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json
ElevenLabs/ProjectSettings/ProjectVersion.txt

- fixed settings config lookup

com.rest.elevenlabs 3.1.2

---

ElevenLabs/Packages/com.rest.elevenlabs/Runtime/TextToSpeech/TextToSpeechRequest.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json

- Fixed text to speech encoding specification

com.rest.elevenlabs 3.2.1

---

ElevenLabs/Packages/com.rest.elevenlabs/package.json
ElevenLabs/Packages/manifest.json

- updated com.utilities.encoder.ogg -> 3.1.1

com.rest.elevenlabs 3.2.2

---

.github/workflows/upm-subtree-split.yml
ElevenLabs/Packages/com.rest.elevenlabs/Editor/ElevenLabsDashboard.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/History/HistoryEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/TextToSpeech/TextToSpeechEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/VoiceGeneration/VoiceGenerationEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Voices/VoicesEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json
ElevenLabs/Packages/manifest.json
ElevenLabs/ProjectSettings/ProjectVersion.txt

- updated com.utilities.rest -> 2.5.0
- updated com.utilities.encoder.ogg 3.1.2
- updated editor version to 2022.3.16f1 LTS

com.rest.elevenlabs 3.2.3

---

.github/workflows/upm-subtree-split.yml
ElevenLabs/Packages/com.rest.elevenlabs/Editor/ElevenLabsDashboard.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Authentication/ElevenLabsAuthentication.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/ElevenLabsClient.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Models/Model.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/TextToSpeech/TextToSpeechEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Voices/Voice.cs
ElevenLabs/Packages/com.rest.elevenlabs/Samples~/TextToSpeech/TextToSpeechDemo.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json

- fixed streaming text to speech endpoint
- voice clip returning empty
- application freeze when encoding pcm to ogg
- updated TextToSpeechDemo
- added client.ctr override to pass in configuration
- updated com.utilities.rest -> 2.5.1
- updated com.utilities.encoder.ogg -> 3.1.3

com.rest.elevenlabs 3.2.4

---

ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Common/VoiceClip.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json

- enabled VoiceClip to be Serializable

com.rest.elevenlabs 3.2.5

---

ElevenLabs/Packages/com.rest.elevenlabs/package.json
ElevenLabs/Packages/manifest.json

- updated com.utilities.rest -> 2.5.2
- updated com.utilities.encoder.ogg -> 3.1.4

com.rest.elevenlabs 3.2.6

---

ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Voices/VoicesEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json

com.rest.elevenlabs 3.2.8

---

ElevenLabs/Packages/com.rest.elevenlabs/package.json

- update com.utilities.rest -> 2.5.3

com.rest.elevenlabs 3.2.9

---

ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Dubbing/DubbingEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Dubbing/DubbingRequest.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/TextToSpeech/TextToSpeechRequest.cs
ElevenLabs/Packages/com.rest.elevenlabs/Tests/Test_Fixture_08_Dubbing.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json
ElevenLabs/Packages/manifest.json

- Fix DubbingRequest.DropBackgroundAudio flag not properly being set
- Added DubbingRequest.UseProfanityFilter flag
- Added previous text input parameter to TextToSpeechRequest

com.rest.elevenlabs 3.3.1

---

ElevenLabs/Packages/com.rest.elevenlabs/Runtime/TextToSpeech/TextToSpeechRequest.cs

Adds previous_text, next_text, previous_request_ids and next_request_ids

Adds previous_text, next_text, previous_request_ids and next_request_ids

---

ElevenLabs/Packages/com.rest.elevenlabs/Samples~/TextToSpeech/TextToSpeechDemo.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json

com.rest.elevenlabs 3.4.1

---

ElevenLabs/Packages/com.rest.elevenlabs/Runtime/TextToSpeech/TextToSpeechRequest.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json

- Removed text length check in TextToSpeechRequest

com.rest.elevenlabs 3.4.2

---

ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Models/Model.cs

update based on this:
https://help.elevenlabs.io/hc/en-us/articles/17883183930129-What-models-do-you-offer-and-what-is-the-difference-between-them
https://elevenlabs.io/blog/meet-flash

Added FlashV2 and FlashV2.5 models

---

ElevenLabs/Packages/com.rest.elevenlabs/Documentation~/README.md
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Authentication/ElevenLabsSettingsInfo.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Dubbing/DubbingEndpoint.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Dubbing/DubbingRequest.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Dubbing/DubbingStream.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Dubbing/DubbingStream.cs.meta
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/Models/Model.cs
ElevenLabs/Packages/com.rest.elevenlabs/Runtime/TextToSpeech/TextToSpeechRequest.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json
README.md

- Added flash models
- Added stream input support to dubbing endpoint
- Fixed http/https protocol in client settings

com.rest.elevenlabs 3.4.3

---

ElevenLabs/Packages/com.rest.elevenlabs/Samples~/TextToSpeech/TextToSpeechDemo.cs
ElevenLabs/Packages/com.rest.elevenlabs/package.json
ElevenLabs/Packages/manifest.json

- updated com.utilities.rest -> 3.3.3
- updated com.utilities.encoder.ogg -> 4.2.2
- updated com.utilities.encoder.wav -> 2.2.2

com.rest.elevenlabs 3.5.2
